/**
 * People API
 * An API that returns a list of people based on a provided date-time.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ER__people_get_200_response_inner.h
 *
 * 
 */

#ifndef ER__people_get_200_response_inner_H
#define ER__people_get_200_response_inner_H

#include <QJsonObject>

#include <QDate>
#include <QString>

#include "ER_Enum.h"
#include "ER_Object.h"

namespace er {

class ER__people_get_200_response_inner : public ER_Object {
public:
    ER__people_get_200_response_inner();
    ER__people_get_200_response_inner(QString json);
    ~ER__people_get_200_response_inner() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getFirstName() const;
    void setFirstName(const QString &first_name);
    bool is_first_name_Set() const;
    bool is_first_name_Valid() const;

    QString getLastName() const;
    void setLastName(const QString &last_name);
    bool is_last_name_Set() const;
    bool is_last_name_Valid() const;

    QDate getDateOfBirth() const;
    void setDateOfBirth(const QDate &date_of_birth);
    bool is_date_of_birth_Set() const;
    bool is_date_of_birth_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_first_name;
    bool m_first_name_isSet;
    bool m_first_name_isValid;

    QString m_last_name;
    bool m_last_name_isSet;
    bool m_last_name_isValid;

    QDate m_date_of_birth;
    bool m_date_of_birth_isSet;
    bool m_date_of_birth_isValid;
};

} // namespace er

Q_DECLARE_METATYPE(er::ER__people_get_200_response_inner)

#endif // ER__people_get_200_response_inner_H
